plugins {
    id 'java-conventions'
    id 'application'
}

application {
    mainClass.set("de.uni_passau.fim.auermich.instrumentation.branchcoverage.BranchCoverage")
}

// If we really need to include the resource directory from the tracer sub project, check out:
// https://stackoverflow.com/questions/20136214/gradle-common-resource-dependency-for-multiple-java-projects/43686346

tasks.register('customFatJar', Jar) {

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes 'Main-Class': 'de.uni_passau.fim.auermich.instrumentation.branchcoverage.BranchCoverage'
    }

    from(sourceSets.main.output)

    dependsOn configurations.runtimeClasspath

    from {
        configurations.runtimeClasspath
                .filter { it.name.endsWith('jar') }
                .collect { zipTree(it) }
    }
}

// useful task that shows were dependencies are locally installed
// https://stackoverflow.com/questions/21417419/how-to-convert-aar-to-jar
tasks.register('showMeCache') {
    configurations.compileClasspath.findAll() { println it }
    configurations.runtimeClasspath.findAll() { println it }
}
