plugins {
    id 'java-conventions'
    id 'application'
}

application {
    mainClass.set("de.uni_passau.fim.auermich.instrumentation.branchdistance.BasicBlockBranchDistance")
}

tasks.register('customFatJar', Jar) {

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes 'Main-Class': 'de.uni_passau.fim.auermich.instrumentation.branchdistance.BasicBlockBranchDistance'
    }

    from(sourceSets.main.output)

    dependsOn configurations.runtimeClasspath

    from {
        configurations.runtimeClasspath
                .filter { it.name.endsWith('jar') }
                .collect { zipTree(it) }
    }
}